### ISSUE TITLE
The "lazy" prop of useTransition is undocumented

### ISSUE THREAD

**Issue by aleclarson** [react-spring/react-spring.io#5]

**Comment by drcmda** [comment]
ah yes, it decides if elements should disappear when there's some idle space, or right when they should logically unmount. lazy can often be the better choice because it batches unmount and creates less renders. but it also means that for transitions that never come to rest (like the x-fade example), it will never, ever unmount items because there's no pause.

**Comment by reaysawa** [comment]
@drcmda is that a good description?

> lazy causes transition states to be disposed of more eagerly, whenever there's a window to do so. Currently this happens when the transition rests (and before onRest is called, if it's defined).
> 
> Since the state is filtered out more often, it can result in less renders.

I can't figure out the last bit from looking at the code because, if it never rests, why does it matter if lazy is set? It seems like lazy only has an impact inside that block.
